package Modelo;
// Generated 31-may-2018 23:27:05 by Hibernate Tools 4.3.1



/**
 * Credenciales generated by hbm2java
 */
public class Credenciales  implements java.io.Serializable {


     private CredencialesId id;

    public Credenciales() {
    }

    public Credenciales(CredencialesId id) {
       this.id = id;
    }
   
    public CredencialesId getId() {
        return this.id;
    }
    
    public void setId(CredencialesId id) {
        this.id = id;
    }




}


