package Modelo;
// Generated 31-may-2018 23:27:05 by Hibernate Tools 4.3.1



/**
 * Usuarioapp generated by hbm2java
 */
public class Usuarioapp  implements java.io.Serializable {


     private int id;
     private String password;

    public Usuarioapp() {
    }

	
    public Usuarioapp(int id) {
        this.id = id;
    }
    public Usuarioapp(int id, String password) {
       this.id = id;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


